name: lets_graduation
description: A new Flutter project.
#ios: 6.21.1
#android: 6.21.1
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6

  get: ^4.6.5

  shared_preferences: ^2.1.2

  cached_network_image: ^3.2.3

  flutter_screenutil: ^5.8.4

  curved_navigation_bar: ^1.0.3

  percent_indicator: ^4.2.3

  syncfusion_flutter_charts: ^22.1.34

  simple_gradient_text: ^1.2.4

  intl: ^0.18.1

  pull_to_refresh: ^2.0.0

  fluttertoast: ^8.2.2

  package_info: ^2.0.2

  google_sign_in: ^6.1.4

  firebase_core: ^2.14.0

  firebase_messaging: ^14.6.3

  firebase_in_app_messaging: ^0.7.3+3

  firebase_auth: ^4.6.3

  cloud_firestore: ^4.8.1

  firebase_storage: ^11.2.3

  location: ^4.4.0

  image_picker: ^0.8.9

  photo_view: ^0.14.0

  youtube_player_flutter: ^8.1.2


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_app.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
