name: lets_graduation
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6

  get: ^4.6.5

  flutter_screenutil: ^5.8.1

  flutter_svg: ^2.0.6

  flutter_hex_color: ^2.0.0

  loading_animation_widget: ^1.2.0+4

  curved_navigation_bar: ^1.0.3

  flutter_image_slideshow: ^0.1.5

  flutter_html: ^3.0.0-beta.1

  url_launcher: ^6.1.11

  curved_nav_bar: ^0.0.2

  percent_indicator: ^4.2.3

  device_info_plus: ^9.0.1

  flutter_credit_card: ^3.0.6

  shape_of_view_null_safe: ^2.0.0

  syncfusion_flutter_charts: ^21.2.5

  google_fonts: ^4.0.4

  simple_gradient_text: ^1.2.4

  intl: ^0.18.1

  pull_to_refresh: ^2.0.0

  fluttertoast: ^8.2.1

  flutter_easyloading: ^3.0.5

  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1

  shared_preferences: ^2.1.1
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0

  crypto: ^3.0.3

  webview_flutter: ^4.2.0

  loading_animations: ^2.2.0

  share: ^2.0.4

  device_info: ^2.0.3

  package_info: ^2.0.2

  path_provider: ^2.0.15

  permission_handler: ^10.2.0

  sentry: ^7.6.1

  uni_links: ^0.5.1

  flutter_spinkit: ^5.2.0

  flutter_swiper_view: ^1.1.8

  dots_indicator: ^3.0.0

  google_sign_in: ^6.1.0

  firebase_core: ^2.13.0

  firebase_messaging: ^14.6.1

  firebase_in_app_messaging: ^0.7.3+1

  firebase_auth: ^4.6.1

  cloud_firestore: ^4.7.1

  firebase_storage: ^11.2.1

  location: ^4.4.0

  image_picker: ^0.8.7+5

  photo_view: ^0.14.0

  flutter_lints: ^2.0.1

  flutter_launcher_icons: ^0.13.1

  cupertino_icons: ^1.0.5

  google_maps_flutter: ^2.2.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_app.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
