import 'package:get/get.dart';

class MyTranslations implements Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "ar": {
          // TODO Auth
          'lets': 'دعونا',
          'get_started': 'البدء',
          'sign_up_to_start_using_our_app': 'قم بالتسجيل لبدء استخدام تطبيقنا',
          'name': 'اسم',
          'phone_number': 'رقم الهاتف',
          'email_address': 'عنوان البريد الإلكتروني',
          'password': 'كلمة المرور',
          'show': 'عرض',
          'sign_in': 'تسجيل الدخول',
          'already_have_an_account': 'هل لديك حساب؟',
          'or_sign_up_with': 'أو قم بالتسجيل مع',
          'enter_username': 'أدخل الاسم ',
          'enter_phone': 'أدخل رقم الهاتف',
          'enter_password': 'أدخل كلمة المرور',
          'validate_password': ' التحقق من كلمة المرور',
          'enter_email': 'أدخل البريد الإلكتروني',
          'enter_valid_email': 'التحقق من البريد الألكتروني',
          'welcome_back': 'مرحبًا بعودتك',
          'sign_in_with_your_account': 'تسجيل الدخول بحسابك',
          'log_in': 'تسجيل الدخول',
          'forgot_your_password': 'نسيت كلمة السر؟',
          'reset_here': 'إعادة التعيين هنا',
          'Choose_the_appropriate_language_to_use_the_application':
              'اختر اللغة المناسبة لاستخدام التطبيق:',
          'english': 'إنجليزي',
          'arabic': 'عربي',
          'done': 'استمر',
          'search_here': 'ابحث هنا',
          'shop_by_category': 'تسوق حسب الاقسام',
          'most_popular': 'الأكثر شهرة',
          'brands': 'العلامات التجارية',
          'products': 'منتجات',
          'order_details': 'تفاصيل الطلب',
          'size': 'مقاس  :',
          'color': 'لون :',
          'quantity': 'كمية:',
          'price': 'سعر:',
          'confirmation': 'تأكيد',
          'settings': 'الأعدادات',
          'applications': 'التطبيقات',
          'profile_visibility': 'رؤية الملف الشخصي',
          'notification': 'إشعار',
          'change_password': 'تغيير كلمة المرور',
          'language': 'اللغة',
          'about': 'عن',
          'privacy': 'خصوصية',
          'terms_and_conditions': 'الأحكام والشروط',
          'help_center': 'مركز المساعدة',
          'problem_title': 'عنوان المشكلة',
          'enter_the_title_of_the_problem': 'أدخل عنوان المشكلة',
          'explanation_of_the_problem': 'شرح المشكلة',
          'Enter_description_of_the_problem': 'أدخل وصفا للمشكلة',
          'send': 'ارسال',
          'about_app': 'حول التطبيق',
          'chose_language': 'اختر اللغة',
          'profile': 'حساب تعريفي',
          'username': 'اسم المستخدم',
          'email': 'بريد إلكتروني',
          'qualifiers': 'المنتجات',
          'analysis': 'تحليل',
          'requests': 'طلباتي',
          'reset_password': 'Reset Password',
          'new_password': 'كلمة المرور الجديدة',
          'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
          'cart': 'عربة التسوق',
          'enter_your_new_password_and_confirm':
              'أدخل كلمة المرور الجديدة وقم بتأكيد \ n كلمة المرور الجديدة لإعادة تعيين كلمة المرور',
          'please_enter_promo_code': ' الرجاء إدخال الرمز الترويجي:',
          'Subtotal': ':المجموع الفرعي',
          'shipping_charges': 'رسوم الشحن:',
          'Total': 'المجموع:',
          'place_your_order': 'ضع طلبك',
          'favorite': ' المفضله',
          'payment_method': 'Payment Method',
          'enter_delivery_address': 'أدخل عنوان التسليم:',
          'add_payment_method': 'إضافة طريقة دفع :',
          'payment': 'قسط',
          'first_name': 'الاسم الأول',
          'last_name': 'الاسم الأخير',
          'please_login_dear_user': 'الرجاء تسجيل الدخول عزيزي المستخدم',
          'logout': 'تسجيل الخروج',
          'cancel': 'إلغاء',
          'the_problem_has_been_sent_successfully': 'تم ارسال المشكله بنجاح',
          'daily': 'يوميًا',
          'weekly': 'أسبوعي',
          'monthly': 'شهريا',
          'annual': 'سنوي',
          'total_sales': 'إجمالي المبيعات',
          'forgot_password': 'هل نسيت كلمة السر',
          'enter_your_email_or_phone_number_we_will_send_you_verification_code':
              'أدخل بريدك الإلكتروني أو رقم هاتفك ، وسنرسل لك \n رمز التحقق',
          'send_code': 'أرسل الرمز',
          'view_our_pages': 'شاهد صفحاتنا على:',
          'Login': 'تسجيل الدخول',
          'please_login': 'الرجاء تسجيل الدخول',
          'text_log_out': 'هل تريد تسجيل الخروج',
          'notificationss': 'إشعارات',
          'verify_code': 'التحقق من كود',
          'enter_your_verification_code':
              'أدخل رمز التحقق من بريدك الإلكتروني  n\ أو رقم الهاتف الذي أرسلناه',
          'add_to_cart': 'أضف الى السلة',
          'select_size': 'أختر الحجم',
          'select_color': 'إختر اللون',
          'select_stone_color': 'حدد لون الحجر',
          'quantity': 'الكمية',
          'total_price': 'السعر الكلي',
          'please_enter_promo_code ': 'الرجاء إدخال الرمز الترويجي',
          'enter_delivery_address': 'أدخل عنوان التسليم:',
          'add_payment_method': 'إضافة طريقة دفع :',
          'search': 'بحث',
          'order_successfully_placed': 'تم تقديم الطلب\n بنجاح .',
          'order_successfully_test':
              'تم الدفع بنجاح! \n فقط انتظر Plantfresher \n حتى تصل إلى المنزل في أسرع وقت ممكن.',
          'done': 'تم',
          'continue': 'إستمر في التسوق',
          'cart_empty': 'عربة التسوق فارغة',
          'add_to_cart_successfully': 'Add to cart successfully',
          'number_of_sales': 'عدد المبيعات',
          'the_number_of_users_who_visited_the_app':
              'عدد المستخدمين الذين \n زاروا التطبيق',
          'next': 'التالي',
          'back': 'رجوع',
          'do_not_have_account': 'لا يوجد لديك حساب',
          'create_account': 'إنشاء حساب',
          'enter_confirm_password': 'أدخل تأكيد كلمة المرور',
          'Password_characters': 'يجب أن تكون كلمة المرور أكثر من 6 أحرف',
          'passwords_do_not_match': 'كلمة المرور غير مطابقة',
          'enter_email': 'أدخل البريد الإلكتروني',
          'enter__valid_email': 'أدخل بريد إلكتروني متاح',
          'verify': 'تأكيد',
          'skip': 'تخطى',
          'dear_requests': 'الطلبات التي قمت بطلبها عزيزي',
        },
        "en": {
          // TODO Auth
          'lets': 'Let’s',
          'get_started': 'Get Started',
          'sign_up_to_start_using_our_app': 'Sign up to start using our app',
          'name': 'Name',
          'phone_number': 'Phone Number',
          'email_address': 'Email Address',
          'password': 'Password',
          'show': 'Show',
          'sign_in': 'Sign In',
          'already_have_an_account': 'Already have an account?',
          'or_sign_up_with': 'Or sign UP with',
          'enter_username': 'Enter UserName',
          'enter_phone': 'Enter Phone',
          'enter_password': 'Enter Password',
          'validate_password': 'Enter Validate Password',
          'enter_email': 'Enter Email',
          'enter_valid_email': 'Enter a Valid Email',
          'welcome_back': 'Welcome back',
          'sign_in_with_your_account': 'Sign in with your account',
          'log_in': 'Log In',
          'forgot_your_password': 'Forgot your password?',
          'reset_here': 'Reset here',
          'Choose_the_appropriate_language_to_use_the_application':
              'Choose the appropriate language to use the application :',
          'english': 'English',
          'arabic': 'Arabic',
          'done': 'Done',
          'search_here': 'search here',
          'shop_by_category': 'Shop by Category',
          'most_popular': 'Most Popular',
          'brands': 'Brands',
          'products': 'products',
          'order_details': 'Order details',
          'size': 'Size :',
          'color': 'Color :',
          'quantity': 'Quantity:',
          'price': 'price:',
          'confirmation': 'confirmation',
          'settings': 'Settings',
          'applications': 'Applications',
          'profile_visibility': 'Profile Visibility',
          'notification': 'Notification',
          'change_password': 'Change Password',
          'language': 'Language',
          'about': 'About',
          'privacy': 'Privacy',
          'terms_and_conditions': 'Terms and conditions',
          'help_center': 'Help Center',
          'problem_title': ' Problem Title ',
          'enter_the_title_of_the_problem': 'Enter the title of the problem',
          'explanation_of_the_problem': ' Explanation of the problem',
          'Enter_description_of_the_problem':
              'Enter a description of the problem',
          'send': 'Send',
          'about_app': 'About the app ',
          'chose_language': 'chose language',
          'profile': 'Profile',
          'username': 'Username',
          'email': 'Email',
          'qualifiers': 'qualifiers',
          'analysis': 'Analysis',
          'requests': 'Requests',
          'reset_password': 'Reset Password',
          'new_password': 'New Password',
          'confirm_new_password': 'Confirm New Password',
          'enter_your_new_password_and_confirm':
              'Enter your new password and confirm the\n        new password to reset password',
          'cart': 'Cart',
          'please_enter_promo_code': ' please Enter Promo Code :',
          'Subtotal': 'Subtotal',
          'shipping_charges': 'Shipping Charges:',
          'Total': 'Total:',
          'place_your_order': 'Place your order',
          'favorite': ' Favorite',
          'payment_method': ' Payment Method',
          'enter_delivery_address': 'Enter Delivery Address :',
          'add_payment_method': 'Add Payment Method :',
          'payment': 'Payment',
          'first_name': 'First Name',
          'last_name': 'Last Name',
          'please_login_dear_user': 'Please login dear user',
          'logout': 'Logout',
          'cancel': 'Cancel',
          'the_problem_has_been_sent_successfully':
              'The problem has been sent successfully',
          'daily': 'Daily',
          'weekly': 'Weekly',
          'monthly': 'Monthly',
          'annual': 'Annual',
          'total_sales': 'Total sales',
          'forgot_password': 'Forgot Password',
          'enter_your_email_or_phone_number_we_will_send_you_verification_code':
              'Enter your email or phone number, we will \n send you verification code',
          'send_code': 'Send code',
          'view_our_pages': 'View our pages on:',
          'Login': 'Login',
          'please_login': 'Please Login',
          'text_log_out': 'Do you want to log out?',
          'notificationss': 'Notificationss',
          'verify_code': 'Verify Code',
          'enter_your_verification_code':
              'Enter your verification code from your email \n          or phone number that we’ve sent',
          'add_to_cart': 'Add to Cart',
          'select_size': 'Select size',
          'select_color': 'Select color',
          'select_stone_color ': 'Select the stone color',
          'quantity': 'Quantity',
          'total_price': 'Total price',
          'enter_delivery_address': 'Enter Delivery Address :',
          'add_payment_method': 'Add Payment Method :',
          'search': 'Search',
          'order_successfully_placed': 'Order Successfully \n Placed. ',
          'order_successfully_test':
              'Your payment was successfully!\n Just wait Plantfresher \n arrive at home asap.',
          'done': 'Done',
          'continue': 'Continue shopping',
          'cart_empty': 'Your Cart is empty',
          'add_to_cart_successfully': 'Add to cart successfully',
          'number_of_sales': 'number of sales',
          'the_number_of_users_who_visited_the_app':
              'The number of users who \n visited the app',
          'next': 'Next',
          'back': 'Back',
          'do_not_have_account': 'You do not have an account',
          'create_account': 'Create an account',
          'enter_confirm_password': 'Enter Confirm Password',
          'Password_characters': 'Password must be more than 6 characters',
          'passwords_do_not_match': 'Passwords do not match',
          'enter_email': 'Enter email',
          'enter__valid_email': 'Enter a valid email',
          'verify': 'Verify',
          'skip': 'Skip',
          'dear_requests': 'Dear requests',
        },
      };
}
